version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing Python version 3.12 ..."
      - pyenv global $PYTHON_312_VERSION
      # Create a virtual environment
      - python3 -m venv venv
      # Activate the virtual environment
      - source venv/bin/activate
      # Upgrade pip to the latest version
      - pip install --upgrade pip
      # Install pytest, selenium, pytest-html, openpyxl, and pytest-xdist
      - pip install pytest selenium pytest-html openpyxl pytest-xdist
      
  pre_build:
    commands:
      - pwd  # Print current directory
      - ls -l  # List files in the current directory
      - chmod +r Configurations/config.ini  # Adjust file permissions

  build:
    commands:
      - pytest -v -s --html=Reports/report.html testCases/test_companySignUp.py

  post_build:
    commands:
      - aws s3 cp Reports/report.html s3://qa-automation-testpurpose/test
